# Generated by Django 4.2.6 on 2024-10-12 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(max_length=3)),
                ('enrolment_no', models.CharField(max_length=20, unique=True)),
                ('date_of_enrolment', models.DateField()),
                ('bar_registration', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('joined_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('months_paid_for', models.IntegerField()),
                ('start_month', models.DateField()),
                ('end_month', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.advocate')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPaymentDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_month', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.advocate')),
            ],
        ),
    ]
