# Generated by Django 4.2.7 on 2025-01-26 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='advocate_pictures/'),
        ),
        migrations.AddField(
            model_name='advocate',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advocate', to=settings.AUTH_USER_MODEL),
        ),
    ]
