# Generated by Django 4.2.7 on 2025-02-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_advocate_picture_advocate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static/images/user'),
        ),
    ]
