# Generated by Django 4.2.7 on 2025-02-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_advocate_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='name',
        ),
    ]
