# Generated by Django 4.2.7 on 2025-02-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_advocate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
    ]
