# Generated by Django 4.2.7 on 2025-02-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_advocate_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='advocate',
        ),
        migrations.AlterField(
            model_name='advocate',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.DeleteModel(
            name='MonthlyPaymentDue',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
