# Generated by Django 4.2.7 on 2025-02-02 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_monthlypaymentdue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='months_paid_for',
        ),
        migrations.AlterField(
            model_name='advocate',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/advocate_pictures/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], default='Pending', max_length=50),
        ),
    ]
