# Generated by Django 4.2.7 on 2025-02-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_payment_months_paid_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
