# Generated by Django 4.2.7 on 2025-03-07 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_advocate_due_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlypaymentdue',
            old_name='due_month',
            new_name='month',
        ),
        migrations.RemoveField(
            model_name='monthlypaymentdue',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt_number',
        ),
        migrations.AddField(
            model_name='monthlypaymentdue',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlypaymentdue',
            name='advocate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_dues', to='payments.advocate'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='advocate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.advocate'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Completed', max_length=20),
        ),
    ]
