# Generated by Django 4.2.7 on 2025-04-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_rename_due_month_monthlypaymentdue_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='kawf_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
