# Generated by Django 4.2.7 on 2025-04-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_advocate_kawf_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='advocate',
        ),
        migrations.AlterField(
            model_name='advocate',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.DeleteModel(
            name='MonthlyPaymentDue',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
