# Generated by Django 4.2.7 on 2025-04-18 15:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_remove_payment_advocate_alter_advocate_due_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('month', models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2)),
                ('year', models.IntegerField()),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('serial_number', models.CharField(max_length=50)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.advocate')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPaymentDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2)),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.advocate')),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('advocate', 'month', 'year')},
            },
        ),
    ]
