# Generated by Django 4.2.7 on 2025-04-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_payment_monthlypaymentdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypaymentdue',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
