# Generated by Django 5.1.6 on 2025-05-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_monthlypaymentdue_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='bar_registration',
        ),
        migrations.AlterField(
            model_name='advocate',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static/images/user'),
        ),
    ]
